services:
  - type: web
    name: neuroguard-api
    env: docker
    region: frankfurt
    plan: free
    rootDir: neurogurad-cloud/backend
    dockerfilePath: ./neurogurad-cloud/backend/Dockerfile
    autoDeploy: true

  - type: static
    name: neuroguard-frontend
    env: static
    buildCommand: npm install && npm run build
    publishPath: ./neurogurad-cloud/frontend/dist
    rootDir: neurogurad-cloud/frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

